name: Update README

on:
    schedule:  
        - cron: '30 12 * * *'

permissions: read-all|write-all

jobs:
    name: Update this repo's README with recent activity
    build:  
        runs-on: ubuntu-latest
        steps:
            - name: Checking Out
              uses: actions/checkout@v3
            - name: Using Repo
              uses: jamesgeorge007/github-activity-readme@master
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
